# Shell variables
# Generated by 'wal'
wallpaper="/home/jordankhwu/.config/i3/share/default_wallpaper"

# Special
background=COLOR0
foreground=COLOR15
cursor=COLOR15

# Colors
color0=COLOR0
color1=COLOR1
color2=COLOR2
color3=COLOR3
color4=COLOR4
color5=COLOR5
color6=COLOR6
color7=COLOR7
color8=COLOR8
color9=COLOR9
color10=COLOR10
color11=COLOR11
color12=COLOR12
color13=COLOR13
color14=COLOR14
color15=COLOR15

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
