# Shell variables
# Generated by 'wal'
wallpaper="/home/jordankhwu/.config/i3/share/default_wallpaper"

# Special
background=#44475A
foreground=#FEFEFE
cursor=#FEFEFE

# Colors
color0=#44475A
color1=#FE5555
color2=#50F97B
color3=#FEB86C
color4=#8BE8FC
color5=#BD98F8
color6=#FE79C6
color7=#FEFEFE
color8=#000000
color9=#FE5555
color10=#50F97B
color11=#FEB86C
color12=#8BE8FC
color13=#BD98F8
color14=#FE79C6
color15=#FEFEFE

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
