# Shell variables
# Generated by 'wal'
wallpaper="/home/jordankhwu/.config/i3/share/default_wallpaper"

# Special
background=#282828
foreground=#EBDBB2
cursor=#EBDBB2

# Colors
color0=#282828
color1=#FB4934
color2=#B8BB26
color3=#FABD2F
color4=#83A598
color5=#D3869B
color6=#8EC07C
color7=#EBDBB2
color8=#928374
color9=#FB4934
color10=#B8BB26
color11=#FABD2F
color12=#83A598
color13=#D3869B
color14=#8EC07C
color15=#EBDBB2

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
